<?php

namespace Wp\Resta\CodeGen\Generators;

/**
 * 型安全なFetchクライアント生成
 */
class FetchClientGenerator
{
    /**
     * 型安全なfetchクライアントを生成
     *
     * @return string 生成されたTypeScriptコード
     */
    public function generate(): string
    {
        $output = "// Auto-generated type-safe API client from OpenAPI schema\n";
        $output .= "// Do not edit this file directly\n\n";

        $output .= "import type { ApiEndpoints } from './endpoints';\n\n";

        $output .= $this->generateClientClass();

        return $output;
    }

    /**
     * クライアントクラスを生成
     *
     * @return string
     */
    private function generateClientClass(): string
    {
        return <<<'TYPESCRIPT'
/**
 * Extract parameter type from ApiEndpoints
 */
type ExtractParams<T> = T extends { params: infer P } ? P : never;

/**
 * Extract response type from ApiEndpoints
 */
type ExtractResponse<T> = T extends { response: infer R } ? R : never;

/**
 * API client configuration
 */
export interface ApiClientConfig {
  baseUrl: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
}

/**
 * Create a type-safe API client
 *
 * @example
 * ```typescript
 * const api = createApiClient({ baseUrl: 'http://localhost:8080/wp-json' });
 * const posts = await api.get('GET /example/posts', { page: 1 });
 * ```
 */
export function createApiClient(config: ApiClientConfig) {
  const { baseUrl, headers = {}, fetch: customFetch = globalThis.fetch } = config;

  /**
   * Make an HTTP request with type safety
   */
  async function request<K extends keyof ApiEndpoints>(
    method: string,
    endpoint: K,
    options?: {
      params?: ExtractParams<ApiEndpoints[K]>;
      body?: any;
      headers?: Record<string, string>;
    }
  ): Promise<ExtractResponse<ApiEndpoints[K]>> {
    // Build URL with path parameters
    // Remove HTTP method prefix (e.g., "GET ", "POST ")
    let url = (endpoint as string).replace(/^(GET|POST|PUT|DELETE|PATCH)\s+/, '');
    const params = options?.params || {};

    // Replace path parameters
    const pathParamNames = new Set<string>();
    url = url.replace(/\{([^}]+)\}/g, (match, paramName) => {
      const value = (params as any)[paramName];
      if (value !== undefined) {
        pathParamNames.add(paramName);
        return String(value);
      }
      return match;
    });

    // Add query parameters (excluding path parameters)
    const queryParams = new URLSearchParams();
    Object.entries(params).forEach(([key, value]) => {
      if (!pathParamNames.has(key)) {
        if (value !== undefined && value !== null) {
          queryParams.append(key, String(value));
        }
      }
    });

    const queryString = queryParams.toString();
    if (queryString) {
      url += (url.includes('?') ? '&' : '?') + queryString;
    }

    // Make request
    const fullUrl = `${baseUrl}${url}`;
    const requestHeaders = {
      'Content-Type': 'application/json',
      ...headers,
      ...options?.headers,
    };

    const response = await customFetch(fullUrl, {
      method,
      headers: requestHeaders,
      body: options?.body ? JSON.stringify(options.body) : undefined,
    });

    if (!response.ok) {
      throw new Error(`API Error: ${response.status} ${response.statusText}`);
    }

    // Handle empty responses
    const contentType = response.headers.get('content-type');
    if (!contentType || !contentType.includes('application/json')) {
      return undefined as ExtractResponse<ApiEndpoints[K]>;
    }

    return response.json();
  }

  return {
    /**
     * GET request
     */
    get<K extends keyof ApiEndpoints & `GET ${string}`>(
      endpoint: K,
      params?: ExtractParams<ApiEndpoints[K]>
    ): Promise<ExtractResponse<ApiEndpoints[K]>> {
      return request('GET', endpoint, { params });
    },

    /**
     * POST request
     */
    post<K extends keyof ApiEndpoints & `POST ${string}`>(
      endpoint: K,
      body: any,
      params?: ExtractParams<ApiEndpoints[K]>
    ): Promise<ExtractResponse<ApiEndpoints[K]>> {
      return request('POST', endpoint, { params, body });
    },

    /**
     * PUT request
     */
    put<K extends keyof ApiEndpoints & `PUT ${string}`>(
      endpoint: K,
      body: any,
      params?: ExtractParams<ApiEndpoints[K]>
    ): Promise<ExtractResponse<ApiEndpoints[K]>> {
      return request('PUT', endpoint, { params, body });
    },

    /**
     * DELETE request
     */
    delete<K extends keyof ApiEndpoints & `DELETE ${string}`>(
      endpoint: K,
      params?: ExtractParams<ApiEndpoints[K]>
    ): Promise<ExtractResponse<ApiEndpoints[K]>> {
      return request('DELETE', endpoint, { params });
    },

    /**
     * PATCH request
     */
    patch<K extends keyof ApiEndpoints & `PATCH ${string}`>(
      endpoint: K,
      body: any,
      params?: ExtractParams<ApiEndpoints[K]>
    ): Promise<ExtractResponse<ApiEndpoints[K]>> {
      return request('PATCH', endpoint, { params, body });
    },
  };
}

TYPESCRIPT;
    }
}
