<?php
namespace Wp\Resta\CodeGen\Generators;

use Wp\Resta\CodeGen\OpenApiParser;

/**
 * TypeScriptインターフェース生成
 */
class InterfaceGenerator
{
    /**
     * OpenAPIスキーマからTypeScriptインターフェースを生成
     *
     * @param OpenApiParser $parser
     * @return string 生成されたTypeScriptコード
     */
    public function generate(OpenApiParser $parser): string
    {
        $schemas = $parser->getSchemas();
        $output = "// Auto-generated TypeScript interfaces from OpenAPI schema\n";
        $output .= "// Do not edit this file directly\n\n";

        foreach ($schemas as $schemaName => $schema) {
            $output .= $this->generateInterface($schemaName, $schema, $parser);
            $output .= "\n";
        }

        return $output;
    }

    /**
     * 単一のインターフェースを生成
     *
     * @param string $name インターフェース名
     * @param array<string, mixed> $schema スキーマ定義
     * @param OpenApiParser $parser
     * @return string 生成されたTypeScriptコード
     */
    private function generateInterface(string $name, array $schema, OpenApiParser $parser): string
    {
        $type = $schema['type'] ?? 'object';

        // array型の場合は type alias として生成
        if ($type === 'array') {
            return $this->generateArrayType($name, $schema, $parser);
        }

        // object型の場合は interface として生成
        if ($type !== 'object') {
            // プリミティブ型の場合は type alias
            return $this->generateTypeAlias($name, $schema);
        }

        $description = $schema['description'] ?? null;
        $properties = $schema['properties'] ?? [];
        $requiredFields = $schema['required'] ?? [];

        $output = '';

        // ドキュメンテーションコメント
        if ($description) {
            $output .= "/**\n";
            $output .= " * {$description}\n";
            $output .= " */\n";
        }

        $output .= "export interface {$name} {\n";

        foreach ($properties as $propName => $propSchema) {
            $isRequired = in_array($propName, $requiredFields, true);
            $propOutput = $this->generateProperty($propName, $propSchema, $isRequired, $parser);
            $output .= "  {$propOutput}\n";
        }

        $output .= "}\n";

        return $output;
    }

    /**
     * プロパティ定義を生成
     *
     * @param string $name プロパティ名
     * @param array<string, mixed> $schema プロパティスキーマ
     * @param bool $isRequired 親スキーマの required 配列に含まれるか
     * @param OpenApiParser $parser
     * @return string プロパティ定義文字列
     */
    private function generateProperty(string $name, array $schema, bool $isRequired, OpenApiParser $parser): string
    {
        $type = $this->convertType($schema, $parser);
        $description = $schema['description'] ?? null;

        $optional = $isRequired ? '' : '?';

        $output = '';

        // プロパティのコメント
        if ($description) {
            $output .= "/** {$description} */\n  ";
        }

        $output .= "{$name}{$optional}: {$type};";

        return $output;
    }

    /**
     * OpenAPI型をTypeScript型に変換
     *
     * @param array<string, mixed> $schema
     * @param OpenApiParser $parser
     * @return string TypeScript型
     */
    private function convertType(array $schema, OpenApiParser $parser): string
    {
        // $ref参照の場合
        if (isset($schema['$ref'])) {
            $schemaName = $parser->extractSchemaNameFromRef($schema['$ref']);
            return $schemaName ?? 'unknown';
        }

        $type = $schema['type'] ?? 'string';

        switch ($type) {
            case 'string':
                // enum の場合
                if (isset($schema['enum'])) {
                    $enumValues = array_map(fn($v) => "'{$v}'", $schema['enum']);
                    return implode(' | ', $enumValues);
                }
                return 'string';

            case 'integer':
            case 'number':
                return 'number';

            case 'boolean':
                return 'boolean';

            case 'array':
                $items = $schema['items'] ?? ['type' => 'unknown'];
                $itemType = $this->convertType($items, $parser);
                return "{$itemType}[]";

            case 'object':
                // インラインオブジェクトの場合
                if (isset($schema['properties'])) {
                    return $this->generateInlineObject($schema, $parser);
                }
                // additionalPropertiesの場合
                if (isset($schema['additionalProperties'])) {
                    $valueType = $this->convertType($schema['additionalProperties'], $parser);
                    return "Record<string, {$valueType}>";
                }
                return 'Record<string, unknown>';

            default:
                return 'unknown';
        }
    }

    /**
     * インラインオブジェクト型を生成
     *
     * @param array<string, mixed> $schema
     * @param OpenApiParser $parser
     * @return string TypeScript型
     */
    private function generateInlineObject(array $schema, OpenApiParser $parser): string
    {
        $properties = $schema['properties'] ?? [];
        $requiredFields = $schema['required'] ?? [];
        $props = [];

        foreach ($properties as $propName => $propSchema) {
            $type = $this->convertType($propSchema, $parser);
            $optional = in_array($propName, $requiredFields, true) ? '' : '?';
            $props[] = "{$propName}{$optional}: {$type}";
        }

        return '{ ' . implode('; ', $props) . ' }';
    }

    /**
     * 配列型のtype aliasを生成
     *
     * @param string $name 型名
     * @param array<string, mixed> $schema スキーマ定義
     * @param OpenApiParser $parser
     * @return string TypeScript type alias
     */
    private function generateArrayType(string $name, array $schema, OpenApiParser $parser): string
    {
        $description = $schema['description'] ?? null;
        $items = $schema['items'] ?? ['type' => 'unknown'];
        $itemType = $this->convertType($items, $parser);

        $output = '';

        if ($description) {
            $output .= "/**\n";
            $output .= " * {$description}\n";
            $output .= " */\n";
        }

        $output .= "export type {$name} = {$itemType}[];\n";

        return $output;
    }

    /**
     * プリミティブ型のtype aliasを生成
     *
     * @param string $name 型名
     * @param array<string, mixed> $schema スキーマ定義
     * @return string TypeScript type alias
     */
    private function generateTypeAlias(string $name, array $schema): string
    {
        $type = $schema['type'] ?? 'unknown';
        $tsType = match ($type) {
            'string' => 'string',
            'integer', 'number' => 'number',
            'boolean' => 'boolean',
            default => 'unknown',
        };

        $description = $schema['description'] ?? null;
        $output = '';

        if ($description) {
            $output .= "/**\n";
            $output .= " * {$description}\n";
            $output .= " */\n";
        }

        $output .= "export type {$name} = {$tsType};\n";

        return $output;
    }
}
