<?php

namespace Test\Resta\Unit\CodeGen\Generators;

use PHPUnit\Framework\TestCase;
use Wp\Resta\CodeGen\Generators\ApiEndpointsGenerator;
use Wp\Resta\CodeGen\OpenApiParser;

class ApiEndpointsGeneratorTest extends TestCase
{
    private ApiEndpointsGenerator $generator;

    protected function setUp(): void
    {
        $this->generator = new ApiEndpointsGenerator();
    }

    private function makeParser(array $paths, array $schemas = []): OpenApiParser
    {
        return new OpenApiParser([
            'openapi' => '3.0.0',
            'paths' => $paths,
            'components' => ['schemas' => $schemas],
        ]);
    }

    private function makeEndpoint(string $path, string $method, array $override = []): array
    {
        return array_merge([
            $path => [
                strtolower($method) => array_merge([
                    'description' => '',
                    'tags' => [],
                    'parameters' => [],
                    'responses' => [],
                ], $override),
            ],
        ]);
    }

    // -------------------------------------------------------------------------
    // generate() — 出力の基本構造
    // -------------------------------------------------------------------------

    public function testGenerateOutputContainsFileHeader(): void
    {
        $parser = $this->makeParser([]);
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('// Auto-generated API endpoints type map', $output);
        $this->assertStringContainsString('// Do not edit this file directly', $output);
    }

    public function testGenerateOutputContainsSchemaImport(): void
    {
        $parser = $this->makeParser([]);
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString("import type * as Schema from './schema';", $output);
    }

    public function testGenerateOutputContainsApiEndpointsInterface(): void
    {
        $parser = $this->makeParser([]);
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('export interface ApiEndpoints {', $output);
        $this->assertStringContainsString('}', $output);
    }

    public function testGenerateWithNoEndpointsProducesEmptyInterface(): void
    {
        $parser = $this->makeParser([]);
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString("export interface ApiEndpoints {\n}", $output);
    }

    // -------------------------------------------------------------------------
    // エンドポイントキー（method + path）
    // -------------------------------------------------------------------------

    public function testGenerateGetEndpointKey(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get'));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString("'GET /posts':", $output);
    }

    public function testGeneratePostEndpointKey(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'post'));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString("'POST /posts':", $output);
    }

    public function testGenerateEndpointWithPathParameter(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts/{id}', 'get', [
            'parameters' => [
                ['name' => 'id', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'integer']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString("'GET /posts/{id}':", $output);
    }

    public function testGenerateEndpointContainsParamsAndResponseKeys(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get'));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('params:', $output);
        $this->assertStringContainsString('response:', $output);
    }

    // -------------------------------------------------------------------------
    // description / tags の JSDoc コメント
    // -------------------------------------------------------------------------

    public function testGenerateEndpointWithDescriptionAddsJsDoc(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'description' => '記事一覧を取得',
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('/**', $output);
        $this->assertStringContainsString('* 記事一覧を取得', $output);
    }

    public function testGenerateEndpointWithTagsAddsTagsInJsDoc(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'description' => 'Get posts',
            'tags' => ['Posts', 'Public'],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('* @tags Posts, Public', $output);
    }

    public function testGenerateEndpointWithoutDescriptionHasNoJsDoc(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'description' => '',
            'tags' => [],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringNotContainsString('/**', $output);
    }

    // -------------------------------------------------------------------------
    // params 型生成
    // -------------------------------------------------------------------------

    public function testGenerateParamsWithNoParametersIsEmptyObject(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'parameters' => [],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('params: {};', $output);
    }

    public function testGenerateRequiredPathParamHasNoOptionalMark(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts/{id}', 'get', [
            'parameters' => [
                ['name' => 'id', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'integer']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('id: number', $output);
        $this->assertStringNotContainsString('id?: number', $output);
    }

    public function testGenerateOptionalQueryParamHasOptionalMark(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'parameters' => [
                ['name' => 'page', 'in' => 'query', 'required' => false, 'schema' => ['type' => 'integer']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('page?: number', $output);
    }

    public function testGenerateMixedPathAndQueryParams(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts/{id}', 'get', [
            'parameters' => [
                ['name' => 'id', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'integer']],
                ['name' => 'format', 'in' => 'query', 'required' => false, 'schema' => ['type' => 'string']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('id: number', $output);
        $this->assertStringContainsString('format?: string', $output);
    }

    public function testGenerateParamTypeIntegerConvertsToNumber(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'parameters' => [
                ['name' => 'count', 'in' => 'query', 'required' => true, 'schema' => ['type' => 'integer']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('count: number', $output);
    }

    public function testGenerateParamTypeBooleanConvertsToBoolean(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'parameters' => [
                ['name' => 'active', 'in' => 'query', 'required' => true, 'schema' => ['type' => 'boolean']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('active: boolean', $output);
    }

    public function testGenerateParamTypeStringConvertsToString(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'parameters' => [
                ['name' => 'search', 'in' => 'query', 'required' => true, 'schema' => ['type' => 'string']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('search: string', $output);
    }

    public function testGenerateParamTypeUnknownDefaultsToString(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'get', [
            'parameters' => [
                ['name' => 'x', 'in' => 'query', 'required' => true, 'schema' => ['type' => 'unknown_type']],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('x: string', $output);
    }

    // -------------------------------------------------------------------------
    // response 型生成
    // -------------------------------------------------------------------------

    public function testGenerateResponseWithNoSchemaIsVoid(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/posts', 'delete', [
            'responses' => [],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('response: void;', $output);
    }

    public function testGenerateResponseWithDirectRefResolvesToSchemaType(): void
    {
        $parser = $this->makeParser(
            $this->makeEndpoint('/posts/{id}', 'get', [
                'responses' => [
                    '200' => [
                        'content' => [
                            'application/json' => [
                                'schema' => ['$ref' => '#/components/schemas/Post'],
                            ],
                        ],
                    ],
                ],
            ]),
            ['Post' => ['type' => 'object', 'properties' => ['id' => ['type' => 'integer']]]]
        );
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('response: Schema.Post;', $output);
    }

    public function testGenerateResponseWithInlineObjectType(): void
    {
        $parser = $this->makeParser($this->makeEndpoint('/status', 'get', [
            'responses' => [
                '200' => [
                    'content' => [
                        'application/json' => [
                            'schema' => [
                                'type' => 'object',
                                'properties' => [
                                    'status' => ['type' => 'string'],
                                    'count' => ['type' => 'integer'],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ]));
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('response: { status: string; count: number };', $output);
    }

    public function testGenerateResponseWithAnyOfNullable(): void
    {
        $parser = $this->makeParser(
            $this->makeEndpoint('/posts/{id}', 'get', [
                'responses' => [
                    '200' => [
                        'content' => [
                            'application/json' => [
                                'schema' => [
                                    'type' => 'object',
                                    'properties' => [
                                        'data' => [
                                            'anyOf' => [
                                                ['$ref' => '#/components/schemas/Post'],
                                                ['type' => 'null'],
                                            ],
                                        ],
                                        'meta' => ['type' => 'object'],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ]),
            ['Post' => ['type' => 'object', 'properties' => ['id' => ['type' => 'integer']]]]
        );
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('data: Schema.Post | null', $output);
        $this->assertStringContainsString('meta: Record<string, unknown>', $output);
    }

    public function testGenerateResponseWithArrayOfRef(): void
    {
        $parser = $this->makeParser(
            $this->makeEndpoint('/posts', 'get', [
                'responses' => [
                    '200' => [
                        'content' => [
                            'application/json' => [
                                'schema' => [
                                    'type' => 'array',
                                    'items' => ['$ref' => '#/components/schemas/Post'],
                                ],
                            ],
                        ],
                    ],
                ],
            ]),
            ['Post' => ['type' => 'object', 'properties' => ['id' => ['type' => 'integer']]]]
        );
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('response: Schema.Post[];', $output);
    }

    public function testGenerateResponseWithInlineObjectContainingRef(): void
    {
        $parser = $this->makeParser(
            $this->makeEndpoint('/posts/{id}', 'get', [
                'responses' => [
                    '200' => [
                        'content' => [
                            'application/json' => [
                                'schema' => [
                                    'type' => 'object',
                                    'properties' => [
                                        'data' => ['$ref' => '#/components/schemas/Post'],
                                        'meta' => ['type' => 'object'],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ]),
            ['Post' => ['type' => 'object', 'properties' => ['id' => ['type' => 'integer']]]]
        );
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString('data: Schema.Post', $output);
        $this->assertStringContainsString('meta: Record<string, unknown>', $output);
    }

    public function testGenerateMultipleEndpoints(): void
    {
        // 同一パスに複数メソッドを持つ場合、array_merge ではなくネストで定義する
        $paths = [
            '/posts' => [
                'get' => ['description' => '', 'tags' => [], 'parameters' => [], 'responses' => []],
                'post' => ['description' => '', 'tags' => [], 'parameters' => [], 'responses' => []],
            ],
            '/posts/{id}' => [
                'delete' => ['description' => '', 'tags' => [], 'parameters' => [], 'responses' => []],
            ],
        ];
        $parser = $this->makeParser($paths);
        $output = $this->generator->generate($parser);

        $this->assertStringContainsString("'GET /posts':", $output);
        $this->assertStringContainsString("'POST /posts':", $output);
        $this->assertStringContainsString("'DELETE /posts/{id}':", $output);
    }
}
