<?php

namespace Test\Resta\Unit\CodeGen\Generators;

use PHPUnit\Framework\TestCase;
use Wp\Resta\CodeGen\Generators\FetchClientGenerator;

class FetchClientGeneratorTest extends TestCase
{
    private FetchClientGenerator $generator;
    private string $output;

    protected function setUp(): void
    {
        $this->generator = new FetchClientGenerator();
        $this->output = $this->generator->generate();
    }

    // -------------------------------------------------------------------------
    // ファイルヘッダー・インポート
    // -------------------------------------------------------------------------

    public function testOutputContainsFileHeader(): void
    {
        $this->assertStringContainsString(
            '// Auto-generated type-safe API client from OpenAPI schema',
            $this->output
        );
        $this->assertStringContainsString(
            '// Do not edit this file directly',
            $this->output
        );
    }

    public function testOutputContainsEndpointsImport(): void
    {
        $this->assertStringContainsString(
            "import type { ApiEndpoints } from './endpoints';",
            $this->output
        );
    }

    // -------------------------------------------------------------------------
    // 型ヘルパー
    // -------------------------------------------------------------------------

    public function testOutputContainsExtractParamsType(): void
    {
        $this->assertStringContainsString(
            'type ExtractParams<T> = T extends { params: infer P } ? P : never;',
            $this->output
        );
    }

    public function testOutputContainsExtractResponseType(): void
    {
        $this->assertStringContainsString(
            'type ExtractResponse<T> = T extends { response: infer R } ? R : never;',
            $this->output
        );
    }

    // -------------------------------------------------------------------------
    // ApiClientConfig インターフェース
    // -------------------------------------------------------------------------

    public function testOutputContainsApiClientConfigInterface(): void
    {
        $this->assertStringContainsString('export interface ApiClientConfig {', $this->output);
    }

    public function testApiClientConfigHasBaseUrl(): void
    {
        $this->assertStringContainsString('baseUrl: string;', $this->output);
    }

    public function testApiClientConfigHasOptionalHeaders(): void
    {
        $this->assertStringContainsString('headers?: Record<string, string>;', $this->output);
    }

    public function testApiClientConfigHasOptionalFetch(): void
    {
        $this->assertStringContainsString('fetch?: typeof fetch;', $this->output);
    }

    // -------------------------------------------------------------------------
    // createApiClient 関数
    // -------------------------------------------------------------------------

    public function testOutputContainsCreateApiClientFunction(): void
    {
        $this->assertStringContainsString(
            'export function createApiClient(config: ApiClientConfig)',
            $this->output
        );
    }

    // -------------------------------------------------------------------------
    // パスパラメータ処理（pathParamNames による除外ロジック）
    // -------------------------------------------------------------------------

    public function testOutputContainsPathParamNamesSet(): void
    {
        // パスパラメータを追跡する Set の宣言
        $this->assertStringContainsString(
            'const pathParamNames = new Set<string>();',
            $this->output
        );
    }

    public function testOutputAddsPathParamToSet(): void
    {
        // 置換成功時に Set へ追加する
        $this->assertStringContainsString(
            'pathParamNames.add(paramName);',
            $this->output
        );
    }

    public function testOutputExcludesPathParamsFromQueryString(): void
    {
        // クエリパラメータ追加時に Set で除外チェックする
        $this->assertStringContainsString(
            'if (!pathParamNames.has(key))',
            $this->output
        );
    }

    public function testPathParameterReplacementUsesRegex(): void
    {
        // {param} 形式のプレースホルダーを置換する正規表現
        $this->assertStringContainsString(
            'url.replace(/\\{([^}]+)\\}/g',
            $this->output
        );
    }

    public function testOutputStripsMethodPrefixFromEndpoint(): void
    {
        // "GET /path" → "/path" への変換
        $this->assertStringContainsString(
            "replace(/^(GET|POST|PUT|DELETE|PATCH)\\s+/, '')",
            $this->output
        );
    }

    // -------------------------------------------------------------------------
    // クエリ文字列の付加
    // -------------------------------------------------------------------------

    public function testOutputUsesUrlSearchParams(): void
    {
        $this->assertStringContainsString('new URLSearchParams()', $this->output);
    }

    public function testOutputSkipsNullAndUndefinedQueryValues(): void
    {
        $this->assertStringContainsString(
            'if (value !== undefined && value !== null)',
            $this->output
        );
    }

    public function testOutputAppendsQueryStringToUrl(): void
    {
        $this->assertStringContainsString("url += (url.includes('?') ? '&' : '?') + queryString;", $this->output);
    }

    // -------------------------------------------------------------------------
    // リクエスト送信・エラーハンドリング
    // -------------------------------------------------------------------------

    public function testOutputSetsContentTypeHeader(): void
    {
        $this->assertStringContainsString("'Content-Type': 'application/json'", $this->output);
    }

    public function testOutputThrowsOnNonOkResponse(): void
    {
        $this->assertStringContainsString('if (!response.ok)', $this->output);
        $this->assertStringContainsString('throw new Error(`API Error:', $this->output);
    }

    public function testOutputHandlesNonJsonResponse(): void
    {
        // Content-Type が application/json でない場合は undefined を返す
        $this->assertStringContainsString(
            "!contentType.includes('application/json')",
            $this->output
        );
        $this->assertStringContainsString('return undefined as', $this->output);
    }

    public function testOutputSerializesBodyAsJson(): void
    {
        $this->assertStringContainsString('JSON.stringify(options.body)', $this->output);
    }

    // -------------------------------------------------------------------------
    // HTTP メソッド別ショートハンド
    // -------------------------------------------------------------------------

    public function testOutputContainsGetMethod(): void
    {
        $this->assertStringContainsString(
            "get<K extends keyof ApiEndpoints & `GET \${string}`>(",
            $this->output
        );
        $this->assertStringContainsString("return request('GET', endpoint, { params });", $this->output);
    }

    public function testOutputContainsPostMethod(): void
    {
        $this->assertStringContainsString(
            "post<K extends keyof ApiEndpoints & `POST \${string}`>(",
            $this->output
        );
        $this->assertStringContainsString("return request('POST', endpoint, { params, body });", $this->output);
    }

    public function testOutputContainsPutMethod(): void
    {
        $this->assertStringContainsString(
            "put<K extends keyof ApiEndpoints & `PUT \${string}`>(",
            $this->output
        );
        $this->assertStringContainsString("return request('PUT', endpoint, { params, body });", $this->output);
    }

    public function testOutputContainsDeleteMethod(): void
    {
        $this->assertStringContainsString(
            "delete<K extends keyof ApiEndpoints & `DELETE \${string}`>(",
            $this->output
        );
        $this->assertStringContainsString("return request('DELETE', endpoint, { params });", $this->output);
    }

    public function testOutputContainsPatchMethod(): void
    {
        $this->assertStringContainsString(
            "patch<K extends keyof ApiEndpoints & `PATCH \${string}`>(",
            $this->output
        );
        $this->assertStringContainsString("return request('PATCH', endpoint, { params, body });", $this->output);
    }

    // -------------------------------------------------------------------------
    // 生成の冪等性
    // -------------------------------------------------------------------------

    public function testGenerateReturnsSameOutputOnMultipleCalls(): void
    {
        $first  = $this->generator->generate();
        $second = $this->generator->generate();

        $this->assertSame($first, $second);
    }
}
