name: ci

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check PSR-4 mapping
      run: composer dump-autoload --dev --optimize --strict-psr

    - name: Run phpstan analyse
      run: vendor/bin/phpstan analyse

    - name: Run test suite
      run: composer run-script test
